// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mediumexample

import (
	"time"
)

type AddressData struct {
	AddressLine string `json:"address_line"`
	City        string `json:"city"`
	Locality    string `json:"locality"`
	Region      string `json:"region"`
	Country     string `json:"country"`
	PostalCode  int    `json:"postal_code"`
}

type UserData struct {
	Email     string      `json:"email"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Phone     string      `json:"phone"`
	Birthdate time.Time   `json:"birthdate"`
	Address   AddressData `json:"address"`
}
